dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notification:
  slack:
    secure: bJ+A0MCn3xO5SSUsgOtKMdME6ZgO+SAb9z3GifsTTqxzJgBjDESF6xo2Prjy/zCvtJW6+vlV5WILDw3+zW/quIeZsFqRR+DxCjW3yIWIJAi4smegoUp+/hghOMzcF4yOIdP9YOk/7Hvao3ZGDEYDxPDStEF4krpfPFyct2ZceJbFPiB7VpB7aRu6WPBGtlotANS7NFCclhUzr5yWdrDsQ06Vf1dtDJatFrcalpHEhuE/6MpNtyFe2dgyeqFZ3aermTuQYWqGiHKPOngE0QXz59z3hPzN25VyJQUN8l5rrI0ZySeZqNUIrpJUJgS+TdB307B4CLzgiK7aWl4MBbYW0tSeKQ2vEYNd7XJz4qLdCCwiXFi3rhq4HCX+lJmSkjGSl9a/5OZgjc+Dk1UBh0EvPCDcOKgx5Nq1f59qofP2R+ugNIe/rqBlERgv8oUagLDHaovobK0o2cQp1NJoMW3Cq0AYYaixGcqtqWpMxhmwc0Ni18U4T6EXxEP+P4VwObBdsvXmFaKWVveO4VYEWLZ4GUgjwo7INp2ebt53JNoUFQxxhizO//H0k73awRmCao/hVOYNs4qcBR/gWyZT/PJ38icN1GEhgKxiqNuzrRAhGOaOXNx8EkfsR/URZR+xDOHfl7g5nhT8EzCHQx2+8J1KPPxoVePQf8UznzaYJSTPIBk=
