dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: MT/7QYJAJMQ1W3gyhe1yEj/lY/CwLPMcvw6OhSxyrIhoQPowwX6MSj5z4uSuhbCFEsO3a1nQMdiAn6e9AeXFQ8Q5QGhUSKBOeByqL7i/uoZMIvfOdGnmOsnxjdlfwvx84vdrZLteC+/3A/VfuT5fM5yUAFbaBkuKr+U6z0G6YsB0VhjHKOF6mS/kQC0QzJbBx4uegV7//SDEqK2eXPLElSthJI8ncXbWVsRnLhhjG/yPpPRafHJYb0iKN2qNgdTkdb2p0h6x8hEgxClh7K+c63s6P+gV4S7Rxw1cZVK70jRFxtDSeRL3SsgEVrUA00O7H2VBfZ+RZjFnfkqjwM/j4WXjzhu9F9zyLERM/6AZPEZE/8smpD6ptI0jv7aHDy7OWT3qKBQJPCpeMDyhl1RmKWlA9BloMCVSUh6GD5u0hHjywlv0MSSNCFGzizUh+UMKnjEMDKIkZ4elM8Tb7VbDTNNPO+F8F4uXN0FUTAG7ItqnvVmkf+wUJ7X+2oegxubxqnrLLAVWqr555SwPVf1Q6hpv2PpeucSbwbZ72loNOnY4ZucqD0exD0ZMMJu93HJzCh18JafN+cQwchsebskxu91nYVxYzJsZ92OEFT7kynBUqwaV5lZ41ElTNqT/+X/0R5s8n+7yPld8MwyyRxP8CQoaoqulyT5ydJX6EQdCr5w=
