dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notification:
  slack:
    secure: a96QB5ihqsu6vZ0fkDkLFsq1f3lbsRIuXRvjnFYvCDYZZYhW6aSzlouKqM5D5leFYcAd6h/ndHrIzYiGSBrMb3307ptAGf8jvgaF7tKDqr87HPL1/+HYCF95wuXFXzvMpn3Y94TsAw6Tx+Ga/mObtZuDG4UbbTu+Kma9YtVGpA0JbO4GLFpOfiRmgnURgKeBDlKwKtmgsxqxmYOlA9MeIP6d3S0oT7XBaBBdsKo0qU8W4FRTC351ec//B08WFeEAkWFkGd7JYm3HIOrLu8DR4TkEYkSE6cctLKebP8j75V6xI8jX0ZQ4dbAwL/Qp0zsWb14gySWSphyVyqx8+b3DJuwen/K/EcL5WGkm1SK/A45mzXnJSM5JME1rI1RkSpaQwoCzQZMhaAH0YIi5y2TwVU5BAz7MR1nBO9IcHDZ8DsHv4LiXESOBTI8eZ+Vgn+7UptoVKmIu2tvqiVzdtoi0wxFgSeg8XD+gqSzAKLUgYN1V+ieC5Ow7V5apfm8r7t+j44yMDZIxaz79/kS839ZK7Uv8imWYLfsptCV8Ienvtzh1qOTpVDQrk+oTz9PnrENVO+cak4BKOVfW4sRLdipw3wHYAvcL6zsG2KSfBB75l/7Vl/Lt5IojPVBSdWgBkW+5Jwh5uZNqBsNJftKtquJ3gV1wlJXnwI7CQZzbTwXpYAc=
