dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: 0XuJUsYPw5R0TVLNzSw/bOO3onCivxcaOY7u4Ba5hAgWny5tV2CxAAuwjaZlF4SJM76i4lcn/hVPe9ll9dQy+wQWfmcIGE3Z78QXYvL7ebCHTqg9C+jBIvAf0MeQq/xmdSyohnTbaZQ1WOoG2pzOpnS3hCJJgWBHPy72aMNd0TsO8tc2q6b5ay5bEllNnyDG29alg7NpNfT8rkPXy/nKwjhev94QQw746CF6cXfrmClLjp/Bn8oNnYH0fpZkzbZDLQtksFDYwLciLmYONzIIHsMCOemyOLQhiD5VRnvB1US4wT595gCxGIyofLiXOQ2h5/ZfKuSSlVa770FhlMsQ1pT4+7ybmGXK4VelaeoFACjORLtqXdxzsydpGcoWl071lfbq6//xislXNe9C4bt1CyaNX3KinK2Ga5FmY7Ep4Km3RkCydkK3JLEjbyxLMQs/bVoAGKpoCnTykYhiUg2gbjKTrR2f4jUKTR0MP1Vf2m389RWLey8oumehY4xDAfeE4VSpHF1x/9SPVvRVEbOqZt3XFbZKjAJ5ryMt2alxnT9WafajPohaoCyTIB1BjvGhAdc0I73QlXvz/oFQHRwq7sOO1fb1nUyO96MW4ZYLTfTc4bnnlI5cZpYhXlcIBTnQir4OE1LM2AsmR+K/PeroywWz2vyTNdh6I/DiGFkY5cw=
